- name: add PostgreSQL repo to the repo list:xp
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main
    create: yes

- name: Download PostgreSQL software key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: install postgresql
  ansible.builtin.apt:
    pkg:
    - postgresql
    - postgresql-contrib
    state: present

- name: start and enable postgresql
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
     
- name: update posstgres.conf
  ansible.builtin.template:
    src: templates/pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf 
  notify: Restart postgresql

- name: create password for user postgres
  ansible.builtin.user:
    name: postgres
    group: postgres
    password: postgres

- name: Create a new database sonarqubedb
  become_user: postgres
  community.general.postgresql_db:
    name: sonarqube
    encoding: UTF-8
    lc_collate: de_DE.UTF-8
    lc_ctype: de_DE.UTF-8

- name: Create user sonarqube
  become_user: postgres
  community.general.postgresql_user:
    db: sonarqube
    name: sonar
    password: sonar
    priv: "ALL"
   
- name: update posstgres.conf
  ansible.builtin.template:
    src: templates/pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf 
  notify: Restart postgresql

