- name: download the zip file
  ansible.builtin.get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.3.zip
    dest: /opt/
    mode: 0755

- name: Extract the zip file
  ansible.builtin.unarchive:
    src: /opt/sonarqube/sonarqube-7.9.3.zip
    dest: /opt/sonarqube/

- name: remove the zip file
  ansible.builtin.file:
    path: /opt/sonarqube/sonarqube-7.9.3.zip
    state: absent
 
    
- name: Configuring the SonarQube Server
  ansible.builtin.template:
    src: templates/sonar.properties.j2
    dest: /opt/sonarqube/conf/sonar.properties
    force: yes

- name: update soanr.sh
  ansible.builtin.template:
    src: templates/sona.sh.j2
    dest: /opt/sonarqube/bin/linux-x86-64/sonar.sh
    force: yes

- name: create a service file
  ansible.builtin.template:
    src: templates/sonarqube.service.j2
    dest:  /etc/systemd/system/sonar.service
    force: yes
